const DATA = {
  meta: { company:"Meridian Holdings Group", subtitle:"Consolidated – 4 operating entities",
    period:"24 months to June 2026", asOf:"30 June 2026", currency:"USD",
    preparedFor:"CEO and Board", preparedBy:"Office of the CFO" },
  headline: { posture:"high",
    verdict:"Group margin looks flat, but Cascade has lost 13 points in two years and only a temporary improvement at Apex is hiding it.",
    summary:[
      "Consolidated gross margin moved 0.3 points, which reads as a stable year and is not one. Cascade Freight has gone from 31.9% to 18.6% while Apex improved enough to offset it at group level. That offset will not repeat — margin improvements plateau, deteriorations compound — so on current trends the consolidated number falls sharply next year with no prior warning in the reporting.",
      "Separately, the largest customer at 10.3% of revenue has cut billings by 90% over five months with no cancellation on file. Nobody escalated it. The forecast almost certainly still assumes this revenue.",
      "Cascade is also the worst collector in the group — 45 to 64 days — and carries the lowest bad debt provision at 0.09% against 0.32% everywhere else. The provision is being set by habit rather than by risk, which means reported earnings at that entity are overstated."],
    callouts:[{label:"Revenue at risk",value:"$2.2M"},{label:"Cash tied up",value:"~$1.1M"},{label:"Actions this week",value:"3"}]},
  kpis:[
    {label:"Revenue (FY2025)",value:"$21.2M",delta:"+8.4% YoY",trend:"up",good:true,severity:"ok",note:"Growth intact, but concentrated in the entities with the thinnest margins."},
    {label:"Gross margin",value:"34.1%",delta:"-0.3 pts",trend:"down",good:false,severity:"high",note:"Stable only in aggregate. The segment view is the one that matters."},
    {label:"Cascade margin",value:"18.6%",delta:"-13.3 pts",trend:"down",good:false,severity:"critical",note:"Two-year decline, still moving. The single largest earnings issue."},
    {label:"Group DSO",value:"52 days",delta:"+11 days",trend:"up",good:false,severity:"high",note:"Driven almost entirely by Cascade at 64 days."},
    {label:"Receivables",value:"$4.98M",delta:"+22% vs PY",trend:"up",good:false,severity:"high",note:"Growing faster than revenue — working capital is absorbing the growth."},
    {label:"Top-4 concentration",value:"28.9%",delta:"+3.1 pts",trend:"up",good:false,severity:"medium",note:"Rising, and the largest of the four is leaving."}],
  ar:{ total:"$4.98M", current:"$1.88M", overdue:"$3.10M", dso:"52 days", dsoPrior:"41 days", dsoTarget:"40 days",
    commentary:"Roughly $1.1M more cash sits with customers than two years ago, concentrated at one entity. At current burn that is close to a month of operating expense.",
    buckets:[{label:"Current",amount:1884000,count:28,severity:"ok"},{label:"1–30 days",amount:1270000,count:13,severity:"low"},
      {label:"31–60 days",amount:469000,count:3,severity:"medium"},{label:"61–90 days",amount:201000,count:2,severity:"high"},
      {label:"90+ days",amount:1158000,count:18,severity:"critical"}],
    agingCommentary:"The shape is wrong. The 90+ bucket is larger than 31–60 and 61–90 combined, which happens when nothing is ever written off rather than when collections are simply slow. $1.16M across 18 invoices sits against a group provision well below that — the write-off has been incurred, it just has not been recognised."},
  concentration:{ commentary:"Customer concentration by share of consolidated revenue. The largest account is the one currently churning, so the effective concentration risk is worse than the profile suggests.",
    threshold:10, items:[{name:"Vantage Consumer Brands",pct:10.3},{name:"Ironbridge Manufacturing",pct:7.6},
      {name:"Northline Grocers Co-op",pct:5.9},{name:"Global Retail Partners",pct:5.1},{name:"Kestrel Auto Components",pct:4.8}]},
  customerRisk:[
    {rank:1,name:"Vantage Consumer Brands",exposure:"$620k",revenuePct:"10.3%",daysPastDue:"142",tier:"critical",
      drivers:"Billings down 90% over five months while payment behaviour slowed in parallel. Both distress signals present at once.",
      action:"CEO contact this week. Assume impairment pending a written payment commitment."},
    {rank:2,name:"Redstone Building Supply",exposure:"$318k",revenuePct:"3.4%",daysPastDue:"96",tier:"high",
      drivers:"Paid at 32 days for two years, now at 96. No dispute logged, no communication.",
      action:"Controller to obtain a payment plan or place on credit hold within 14 days."},
    {rank:3,name:"Ferrous Metals Trading",exposure:"$240k",revenuePct:"2.8%",daysPastDue:"74",tier:"high",
      drivers:"Balance disputed since March over accessorial charges. Unresolved for four months.",
      action:"CFO and VP Sales to settle the dispute this month — it is a service issue, not a collections issue."},
    {rank:4,name:"Quarry Stone Materials",exposure:"$187k",revenuePct:"2.1%",daysPastDue:"61",tier:"medium",
      drivers:"Drifting steadily but still communicating and still ordering.",action:"Standard escalation. Review terms at renewal."},
    {rank:5,name:"Meadowvale Farms",exposure:"$96k",revenuePct:"1.6%",daysPastDue:"38",tier:"low",
      drivers:"Seasonal payment pattern consistent with prior years.",action:"No action."}],
  collections:[
    {priority:1,customer:"Redstone Building Supply",amount:"$318k",age:"96 days",likelihood:"High",owner:"Controller",dueBy:"14 days",
      action:"Solvent, undisputed, simply not chased. Fastest cash available — call this week."},
    {priority:2,customer:"Ferrous Metals Trading",amount:"$240k",age:"74 days",likelihood:"High",owner:"VP Sales",dueBy:"30 days",
      action:"Resolve the accessorial dispute; the cash follows the resolution."},
    {priority:3,customer:"Vantage Consumer Brands",amount:"$620k",age:"142 days",likelihood:"Moderate",owner:"CEO",dueBy:"7 days",
      action:"Executive-level contact. Exposure justifies senior attention now, not later."},
    {priority:4,customer:"Quarry Stone Materials",amount:"$187k",age:"61 days",likelihood:"High",owner:"Collections",dueBy:"30 days",
      action:"Structured follow-up on normal cadence."},
    {priority:5,customer:"Aged book (11 accounts)",amount:"$294k",age:"180+ days",likelihood:"Doubtful",owner:"Controller",dueBy:"This quarter",
      action:"Assess for write-off. Effort here is better spent on the four above."}],
  forecast:{ horizon:"Next 13 weeks", commentary:"Assumes historical payment behaviour holds at every entity except Cascade, where the current run rate is used. It does not assume any recovery of the 90+ book.",
    accuracyNote:"The prior three forecasts ran 12% optimistic on average. Treat the expected case as a ceiling rather than a plan.",
    series:[{label:"Wk 1–2",expected:620000,atRisk:90000},{label:"Wk 3–4",expected:540000,atRisk:140000},
      {label:"Wk 5–6",expected:610000,atRisk:120000},{label:"Wk 7–8",expected:480000,atRisk:190000},
      {label:"Wk 9–10",expected:560000,atRisk:160000},{label:"Wk 11–13",expected:590000,atRisk:200000}],
    totals:{expected:"$3.4M",atRisk:"$0.9M"}},
  alerts:[
    {severity:"critical",title:"Largest customer has effectively churned without anyone recording it",
      finding:"Vantage Consumer Brands, 10.3% of revenue, fell from $155k to $15k monthly over five months. No cancellation on file.",
      risk:"About $2.2M of annualised revenue, almost certainly still in the forecast. A decline this size running five months unflagged suggests the same blind spot applies to other accounts.",
      action:"CEO to make direct executive contact. Rerun the forecast with this account at zero and report what breaks.",owner:"CEO",timing:"This week"},
    {severity:"critical",title:"Segment margin collapse invisible at group level",
      finding:"Cascade gross margin 31.9% to 18.6% over 24 months, offset in the consolidated view by Apex improving 42.0% to 45.4%.",
      risk:"Roughly $1.4M of annual gross profit, compounding. The offset is temporary, so the group figure will fall sharply and without warning.",
      action:"Report segment margin to the board from this month. Retire the consolidated headline.",owner:"CFO",timing:"This week"},
    {severity:"high",title:"Bad debt provision is set inversely to risk",
      finding:"Cascade reserves 0.09% of revenue against 0.32% at every other entity, while carrying the group's worst aging.",
      risk:"Earnings at Cascade are overstated. $1.16M sits beyond 90 days against a provision materially below it.",
      action:"Reset provisioning to a risk-based rate and book the catch-up this period rather than spreading it.",owner:"Controller",timing:"Before close"},
    {severity:"medium",title:"Vendor spend fragmented across name variants",
      finding:"Three spellings of the same fuel supplier total $3.50M when combined, ranking each individually outside the top five.",
      risk:"Not a loss — a forgone negotiation. The group is a top-three customer of this supplier and is not pricing like one.",
      action:"Merge the vendor master and reopen terms at the next renewal.",owner:"Procurement / Controller",timing:"This quarter"},
    {severity:"medium",title:"Control gaps suggest an error bar on the whole pack",
      finding:"Intercompany balances out by $100k, five of 24 months missing FX revaluation, and unreconciled suspense items outstanding.",
      risk:"Individually immaterial. Together they mean consolidated figures carry an unquantified error, which matters more as the group grows.",
      action:"Clear intercompany and FX before year-end close; put a monthly reconciliation sign-off in place.",owner:"Controller",timing:"30 days"}],
  risks:[
    {title:"Customer concentration with an active churn event",category:"Concentration",severity:"critical",
      likelihood:"Occurring",impact:"$2.2M revenue",
      description:"Top four customers are 28.9% of revenue and the largest is leaving. Concentration was tolerable while the base was stable; it is not while one of the four is exiting and the reporting did not catch it.",
      mitigation:"CEO-led retention attempt this week, forecast rerun at zero, and a standing alert on any account declining more than 30% over two periods. Owner: CEO."},
    {title:"Structural margin erosion at Cascade",category:"Earnings",severity:"critical",
      likelihood:"Occurring",impact:"~$1.4M annual gross profit",
      description:"Thirteen points over two years with no sign of stabilising. Cause is not yet established — input cost, mix, or price concession — and the remedy differs entirely by cause.",
      mitigation:"Rate-versus-volume analysis within 30 days, then a pricing decision. Owner: CFO with Cascade GM."},
    {title:"Working capital absorbing growth",category:"Liquidity",severity:"high",
      likelihood:"Likely",impact:"~$1.1M cash",
      description:"Receivables growing faster than revenue while DSO extends. Profit is not converting to cash at the rate the P&L implies.",
      mitigation:"Weekly collections cadence on the top eight balances; no terms changes without CFO sign-off. Owner: Controller."},
    {title:"Under-provisioning at the highest-risk entity",category:"Credit",severity:"high",
      likelihood:"Likely",impact:"$0.9M–1.2M",
      description:"Aged balances exceed the provision. The loss is incurred; recognition is lagging.",
      mitigation:"Risk-based provisioning policy applied consistently across entities, effective this close. Owner: Controller."},
    {title:"Management reporting did not surface a 90% customer decline",category:"Reporting",severity:"high",
      likelihood:"Occurring",impact:"Unquantified",
      description:"A five-month decline in the largest account produced no alert. Whatever failed here is not specific to this customer.",
      mitigation:"Exception reporting on customer revenue variance, reviewed monthly by CFO. Owner: FP&A."},
    {title:"Vendor dependency masked by fragmented naming",category:"Concentration",severity:"medium",
      likelihood:"Possible",impact:"Pricing exposure",
      description:"Consolidated spend with one supplier is materially larger than any single vendor record shows, so dependency has never been assessed.",
      mitigation:"Vendor master cleanup and an annual concentration review. Owner: Procurement."}],
  actions:[
    {rank:1,action:"CEO to make direct contact with Vantage Consumer Brands and establish whether the account is recoverable.",
      rationale:"A 90% decline is not recoverable at account-manager level, and every week of delay reduces the odds further.",
      owner:"CEO",timing:"This week",impact:"$2.2M revenue at stake",effort:"Low"},
    {rank:2,action:"Rerun the 12-month forecast with Vantage at zero and report what breaks.",
      rationale:"The plan almost certainly still contains this revenue. Leadership needs to see the gap before committing spend against it.",
      owner:"FP&A",timing:"This week",impact:"Restores forecast credibility",effort:"Low"},
    {rank:3,action:"Move board and management reporting to segment margin. Retire the consolidated headline.",
      rationale:"The consolidated figure concealed a 13-point decline for two years. It will conceal the next one.",
      owner:"CFO",timing:"Next reporting cycle",impact:"Visibility on ~25% of group revenue",effort:"Low"},
    {rank:4,action:"Split Cascade's fuel and purchased transport spend between rate and volume, and bring pricing recommendations to the next review.",
      rationale:"Cost inflation and mix shift call for completely different remedies. Acting before knowing which risks fixing the wrong thing.",
      owner:"CFO with Cascade GM",timing:"30 days",impact:"Determines the path back to ~6 of the 13 points lost",effort:"Medium",
      tradeoff:"Repricing to recover margin will cost volume at an entity already losing share."},
    {rank:5,action:"Reset the bad debt provision to a risk-based rate across all entities and book the catch-up this period.",
      rationale:"Reserving least where risk is highest overstates earnings and delays a loss already incurred.",
      owner:"Controller",timing:"Before close",impact:"~$0.9M charge, correctly placed",effort:"Low",
      tradeoff:"Reduces reported earnings this period. Better taken now than discovered at audit."},
    {rank:6,action:"Place the eight balances over 90 days on a weekly call cadence with a named owner each.",
      rationale:"The 90+ bucket is larger than the two beneath it combined, which is a chasing problem before it is a credit problem.",
      owner:"Controller",timing:"From Monday",impact:"~$400k recovery target in 60 days",effort:"Medium"},
    {rank:7,action:"Merge duplicate vendor records and reopen fuel supply terms at renewal.",
      rationale:"The group is a top-three customer of this supplier and has never negotiated as one.",
      owner:"Procurement",timing:"This quarter",impact:"2–4% of $3.5M annual spend",effort:"Low"}],
  nextSteps:[
    {when:"This week",item:"CEO contact with Vantage; forecast rerun at zero; segment margin added to the board pack.",owner:"CEO / FP&A / CFO"},
    {when:"Before close",item:"Provision reset booked; intercompany and FX differences cleared.",owner:"Controller"},
    {when:"30 days",item:"Cascade rate-versus-volume analysis returned with pricing recommendations.",owner:"CFO"},
    {when:"30 days",item:"Customer-level aging for Cascade produced so the DSO cause can be established.",owner:"FP&A"},
    {when:"Next review",item:"Exception reporting on customer revenue variance live and tested against the last 24 months.",owner:"FP&A"}],
  dataNotes:[
    "Cascade's fuel spend is not split between rate and volume, so the margin decline cannot yet be attributed to input cost versus pricing. This blocks the pricing decision.",
    "No customer-level aging for Cascade, so it is not possible to tell whether the DSO slippage is broad or concentrated in a few distressed accounts. The two have different remedies.",
    "Whether Vantage has formally terminated is not stated. Treated here as churn on the basis of the billing pattern.",
    "Cash balance and facility headroom were not supplied, so runway and covenant proximity could not be assessed. Both are needed before the provision charge is taken."]
};
